In [1]:
import numpy as np

In [2]:
x = np.array([1, 1, 8, np.nan, 10])

In [4]:
np.isnan(x)

array([False, False, False,  True, False])

In [6]:
np.count_nonzero(np.isnan(x))

1

In [7]:
print(np.nan == np.nan)

False


In [15]:
x = np.array([1, 2, 3])

In [16]:
x

array([1, 2, 3])

In [18]:
y = np.array(x)
z = np.asarray(x)

In [25]:
a = y == z

In [26]:
a

array([ True,  True, False])

In [20]:
x[2] = 1

In [21]:
x

array([1, 2, 1])

In [22]:
y

array([1, 2, 3])

In [23]:
z

array([1, 2, 1])

In [24]:
y == z

array([ True,  True, False])

In [27]:
a = np.asarray([0, 1, 2, 3, 4])
d = np.asarray([[(1.5, 2, 3), (4, 5, 6)],
              [(3, 2, 1), (4, 5, 6)]])

In [28]:
a

array([0, 1, 2, 3, 4])

In [29]:
d

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [30]:
def f(x, y):
    return 10 * x + y
x = np.fromfunction(f, (5, 4), dtype=int)

In [31]:
x

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [32]:
x = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

In [33]:
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [34]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.zeros_like(x)

In [35]:
y

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
z = np.zeros((4,3))

In [38]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
y = np.ones_like(np.array(range(4)))

In [47]:
y

array([1, 1, 1, 1])

In [52]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [54]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
x = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [61]:
y = np.identity(5)

In [68]:
np.logspace(0, 1, 2)

array([ 1., 10.])

In [69]:
x = np.linspace(start=0, stop=1, num=5)
x = [10 ** i for i in x]

In [70]:
x

[1.0, 1.7782794100389228, 3.1622776601683795, 5.623413251903491, 10.0]

In [71]:
print(np.around(x, 2))
# [ 1.    1.78  3.16  5.62 10.  ]

[ 1.    1.78  3.16  5.62 10.  ]


In [72]:
x = np.random.random([2, 3])

In [73]:
x

array([[0.7284168 , 0.58448962, 0.1898773 ],
       [0.48336498, 0.38262769, 0.88428803]])

In [74]:
np.around(x, decimals=2)

array([[0.73, 0.58, 0.19],
       [0.48, 0.38, 0.88]])

In [75]:
0 * np.nan

nan

In [76]:
np.inf > np.nan

False

In [77]:
np.nan - np.nan

nan

In [79]:
a = 0.3
b = 3 * 0.1

In [80]:
a == b

False

In [85]:
type(a)

float

In [86]:
type(b)

float

In [87]:
a

0.3

In [88]:
b

0.30000000000000004

In [101]:
np.datetime64('2020-05-18')

numpy.datetime64('2020-05-18')

In [106]:
np.datetime64('today')

numpy.datetime64('2023-02-28')

In [109]:
x = np.random.randint(1, 100, [2, 2, 3])

In [110]:
x

array([[[14, 40, 88],
        [37, 78, 62]],

       [[ 1, 72, 30],
        [24, 83,  6]]])

In [111]:
x[..., 2]

array([[88, 62],
       [30,  6]])

In [112]:
x[..., :2]

array([[[14, 40],
        [37, 78]],

       [[ 1, 72],
        [24, 83]]])

In [123]:
a=np.array([[1,2],[3,4],[5,6]])
b=a[0,0]

In [125]:
b

1

In [126]:
x = np.array(range(10))
x.shape

(10,)

In [127]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

In [141]:
y = x.flat
y2 = x.flatten()
y3 = x.ravel()
y4 = np.ravel(x, order='F')

In [142]:
y

In [143]:
y2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [144]:
y3

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [145]:
y4

array([11, 16, 21, 26, 31, 12, 17, 22, 27, 32, 13, 18, 23, 28, 33, 14, 19,
       24, 29, 34, 15, 20, 25, 30, 35])

In [146]:
x[0][0] = 1

In [147]:
x

array([[ 1, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [148]:
y

In [149]:
y2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [150]:
y3

array([ 1, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [151]:
y4

array([11, 16, 21, 26, 31, 12, 17, 22, 27, 32, 13, 18, 23, 28, 33, 14, 19,
       24, 29, 34, 15, 20, 25, 30, 35])

In [152]:
x = np.random.randint(12, size=[2, 2, 3])
y = np.reshape(x, -1)

In [153]:
x

array([[[ 8, 11,  7],
        [ 8,  3,  6]],

       [[ 8,  8, 11],
        [ 0,  9,  4]]])

In [154]:
y

array([ 8, 11,  7,  8,  3,  6,  8,  8, 11,  0,  9,  4])

In [155]:
x = np.random.randint(1, 100, [2, 2, 3])

In [156]:
y1 = x.T

In [161]:
y2 = np.transpose(x)

In [159]:
x

array([[[92, 52, 88],
        [55, 75, 86]],

       [[84, 17, 16],
        [29, 88,  7]]])

In [158]:
y1

array([[[92, 84],
        [55, 29]],

       [[52, 17],
        [75, 88]],

       [[88, 16],
        [86,  7]]])

In [162]:
y2

array([[[92, 84],
        [55, 29]],

       [[52, 17],
        [75, 88]],

       [[88, 16],
        [86,  7]]])

In [168]:
x = np.array([[11, 12, 13, 14],
              [16, 17, 18, 19],
              [21, 22, 23, 24]])
np.split(x, [1, 3])

[array([[11, 12, 13, 14]]),
 array([[16, 17, 18, 19],
        [21, 22, 23, 24]]),
 array([], shape=(0, 4), dtype=int32)]

In [169]:
x = np.array([[1, 2], [3, 4]])
y = np.tile(x, (1, 3))
print(y)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [170]:
x = np.array([[1, 2], [3, 4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [172]:
np.repeat(x, [2, 3], axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [177]:
a=np.array([1,1,2,3,3,4,4])
b=np.unique(a,return_index=True, return_inverse=True,return_counts=True)

In [178]:
b

(array([1, 2, 3, 4]),
 array([0, 2, 3, 5], dtype=int64),
 array([0, 0, 1, 2, 2, 3, 3], dtype=int64),
 array([2, 1, 2, 2], dtype=int64))