In [2]:
import numpy as np

In [3]:
np.random.seed(20200614)
size = 50000
x = np.random.randn(size)

In [4]:
x

array([ 0.79308468,  0.8177404 ,  0.98209304, ...,  0.1732716 ,
        0.21571349, -0.78804003])

In [11]:
x < 1

array([ True,  True,  True, ...,  True,  True,  True])

In [6]:
np.sum(x < 2)

48914

In [7]:
np.sum(x < 3)

49939

In [12]:
np.random.seed(20200614)
x = np.random.choice(10, 3, replace=False, p=[0.05, 0, 0.05, 0.9, 0, 0, 0, 0, 0, 0])
print(x)

[3 0 2]


In [13]:
np.random.seed(20200623)
x = np.random.randint(0, 20, size=[4, 5])

In [14]:
x

array([[10,  2,  1,  1, 16],
       [18, 11, 10, 14, 10],
       [11,  1,  9, 18,  8],
       [16,  2,  0, 15, 16]])

In [21]:
x.sort()

In [22]:
x

array([[ 0,  1,  2, 10, 16],
       [ 1,  2,  9, 11, 16],
       [ 1,  8, 11, 14, 18],
       [10, 10, 15, 16, 18]])

In [23]:
x.sort(axis=0)

In [24]:
x

array([[ 0,  1,  2, 10, 16],
       [ 1,  2,  9, 11, 16],
       [ 1,  8, 11, 14, 18],
       [10, 10, 15, 16, 18]])

In [25]:
np.random.seed(20200623)
x = np.random.randint(0, 20, size=[4, 5])
np.percentile(x, [25, 50])

array([ 2., 10.])

In [26]:
x

array([[10,  2,  1,  1, 16],
       [18, 11, 10, 14, 10],
       [11,  1,  9, 18,  8],
       [16,  2,  0, 15, 16]])

In [27]:
np.percentile(x, [25, 50], axis=0)

array([[10.75,  1.75,  0.75, 10.75,  9.5 ],
       [13.5 ,  2.  ,  5.  , 14.5 , 13.  ]])

In [28]:
x = np.array(range(11, 36)).reshape(5,5)

In [29]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [30]:
np.average(x)

23.0

In [31]:
x2 = np.arange(1, 26).reshape([5, 5])

In [32]:
z = np.average(x, weights=x2)

In [33]:
z

27.0

In [35]:
z = np.average(x, axis=0, weights=x2)

In [36]:
z

array([25.54545455, 26.16666667, 26.84615385, 27.57142857, 28.33333333])

In [37]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T

In [38]:
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])