In [1]:
import torch
import numpy as np

In [13]:
x = np.arange(4)
y = np.ones((3, 4))
print((x+y).shape)

(3, 4)


In [14]:
x = np.arange(4).reshape(4, 1)
y = np.ones(5)
print((x+y).shape)

(4, 5)


In [16]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.arange(1, 6) 
np.add(x, y)== x + y

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
np.subtract(x, y) == x - y

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [18]:
np.multiply(x, y) == x * y

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [19]:
np.divide(x, y) == x / y

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
np.floor_divide(x, y) == x // y

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [22]:
np.power(x, np.full([1, 5], 2)) == x ** np.full([1, 5], 2)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [23]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
np.cumprod(x)

array([         11,         132,        1716,       24024,      360360,
           5765760,    98017920,  1764322560,  -837609728,   427674624,
         391232512,    17180672,   395155456,   893796352,   870072320,
        1147043840,   905412608,  -418250752,   755630080,  1194065920,
       -1638662144,  -897581056,   444596224, -2063597568,   788529152],
      dtype=int32)

In [24]:
x = np.array([11, 17, 23, 29, 35])
y = np.clip(x, a_min=20, a_max=30)
y

array([20, 20, 23, 29, 30])

In [25]:
np.all([1.0, np.nan])

True

In [29]:
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
y1 = np.array([np.take(x[i], np.argsort(x[i])) for i in range(5)])
y2 = np.sort(x)

In [30]:
y1 == y2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [31]:
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])

In [32]:
x

array([[ 9, 25,  4],
       [ 8, 24, 16],
       [17, 11, 21],
       [ 3, 22,  3],
       [ 3, 15,  3],
       [18, 17, 25],
       [16,  5, 12],
       [29, 27, 17]])

In [33]:
z = np.partition(x, kth=2, axis=0)

In [34]:
z

array([[ 3,  5,  3],
       [ 3, 11,  3],
       [ 8, 15,  4],
       [ 9, 22, 21],
       [17, 24, 16],
       [18, 17, 25],
       [16, 25, 12],
       [29, 27, 17]])

In [35]:
z2 = np.partition(x, kth=1, axis=0)

In [36]:
z2

array([[ 3,  5,  3],
       [ 3, 11,  3],
       [17, 24, 21],
       [ 9, 22,  4],
       [ 8, 15, 16],
       [18, 17, 25],
       [16, 25, 12],
       [29, 27, 17]])

In [37]:
z = np.partition(x, kth=0, axis=0)

In [38]:
z

array([[ 3,  5,  3],
       [ 8, 24, 16],
       [17, 11, 21],
       [ 9, 22,  4],
       [ 3, 15,  3],
       [18, 17, 25],
       [16, 25, 12],
       [29, 27, 17]])

In [40]:
x = np.array([5, 1, 6, 7, 8, 4])

In [41]:
y = np.partition(x, kth=2, axis=0)

In [42]:
y

array([1, 4, 5, 7, 8, 6])

In [70]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
y = np.nonzero(x)

In [81]:
x[y]

array([3, 4, 5, 6])

In [82]:
np.transpose(y)

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]], dtype=int64)

In [83]:
x = np.array([[[0, 1], [1, 0]], [[0, 1], [1, 0]], [[0, 0], [1, 0]]])

In [84]:
y = np.nonzero(x)

In [85]:
x[y]

array([1, 1, 1, 1, 1])

In [86]:
np.transpose(y)

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [1, 1, 0],
       [2, 1, 0]], dtype=int64)

In [87]:
y

(array([0, 0, 1, 1, 2], dtype=int64),
 array([0, 1, 0, 1, 1], dtype=int64),
 array([1, 0, 1, 0, 0], dtype=int64))

In [88]:
x = np.arange(10)
y = np.where(x < 5, x, 10 * x)
z = np.where(x > 7)

In [89]:
y

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [90]:
z

(array([8, 9], dtype=int64),)

In [91]:
x = np.array(['a', 'b', 'b', 'c', 'a'])
y, index, inverse, counts = np.unique(x, return_index=True, return_inverse=True, return_counts=True)

In [92]:
y, index, inverse, counts

(array(['a', 'b', 'c'], dtype='<U1'),
 array([0, 1, 3], dtype=int64),
 array([0, 1, 1, 2, 0], dtype=int64),
 array([2, 2, 1], dtype=int64))

In [95]:
from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([3])