In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data/learn_pandas.csv',
                 usecols = ['Grade', 'Name', 'Gender', 'Height',
                            'Weight', 'Transfer'])

In [3]:
df

Grade            Name  Gender  Height  Weight Transfer
0     Freshman    Gaopeng Yang  Female   158.9    46.0        N
1     Freshman  Changqiang You    Male   166.5    70.0        N
2       Senior         Mei Sun    Male   188.9    89.0        N
3    Sophomore    Xiaojuan Sun  Female     NaN    41.0        N
4    Sophomore     Gaojuan You    Male   174.0    74.0        N
..         ...             ...     ...     ...     ...      ...
195     Junior    Xiaojuan Sun  Female   153.9    46.0        N
196     Senior         Li Zhao  Female   160.9    50.0        N
197     Senior  Chengqiang Chu  Female   153.9    45.0        N
198     Senior   Chengmei Shen    Male   175.3    71.0        N
199  Sophomore     Chunpeng Lv    Male   155.7    51.0        N

[200 rows x 6 columns]

In [4]:
df.isna()

Grade   Name  Gender  Height  Weight  Transfer
0    False  False   False   False   False     False
1    False  False   False   False   False     False
2    False  False   False   False   False     False
3    False  False   False    True   False     False
4    False  False   False   False   False     False
..     ...    ...     ...     ...     ...       ...
195  False  False   False   False   False     False
196  False  False   False   False   False     False
197  False  False   False   False   False     False
198  False  False   False   False   False     False
199  False  False   False   False   False     False

[200 rows x 6 columns]

In [5]:
df.isna().mean()

Grade       0.000
Name        0.000
Gender      0.000
Height      0.085
Weight      0.055
Transfer    0.060
dtype: float64

In [7]:
df[df.Height.isna()]

Grade          Name  Gender  Height  Weight Transfer
3    Sophomore  Xiaojuan Sun  Female     NaN    41.0        N
12      Senior      Peng You  Female     NaN    48.0      NaN
26      Junior     Yanli You  Female     NaN    48.0        N
36    Freshman  Xiaojuan Qin    Male     NaN    79.0        Y
60    Freshman    Yanpeng Lv    Male     NaN    65.0        N
91   Sophomore   Yanfeng Han    Male     NaN     NaN        N
98   Sophomore  Xiaojuan Chu    Male     NaN    68.0        N
102     Junior  Chengli Zhao    Male     NaN     NaN      NaN
111   Freshman    Gaoquan Xu  Female     NaN    52.0        N
130     Senior      Mei Feng  Female     NaN    51.0        N
133   Freshman   Gaojuan Qin  Female     NaN    41.0        N
145     Junior   Gaoquan Chu  Female     NaN    51.0        N
152     Junior   Chengli Sun    Male     NaN    62.0        N
154     Junior   Yanpeng Han  Female     NaN    44.0        N
178  Sophomore        Li Qin    Male     NaN    76.0        N
181  Sophomore   Yanjuan You    Male     NaN    55.0        N
186   Freshman  Yanjuan Zhao  Female     NaN    53.0        N

In [19]:
sub_set = df[['Height', 'Weight']]
df[sub_set.isna().any(1)].shape

(26, 6)

In [12]:
res = df.dropna(how = 'any', subset = ['Height', 'Weight'])

In [20]:
res.shape

(174, 6)

In [21]:
df.dropna(1, thresh=df.shape[0]-15)

Grade            Name  Gender  Weight Transfer
0     Freshman    Gaopeng Yang  Female    46.0        N
1     Freshman  Changqiang You    Male    70.0        N
2       Senior         Mei Sun    Male    89.0        N
3    Sophomore    Xiaojuan Sun  Female    41.0        N
4    Sophomore     Gaojuan You    Male    74.0        N
..         ...             ...     ...     ...      ...
195     Junior    Xiaojuan Sun  Female    46.0        N
196     Senior         Li Zhao  Female    50.0        N
197     Senior  Chengqiang Chu  Female    45.0        N
198     Senior   Chengmei Shen    Male    71.0        N
199  Sophomore     Chunpeng Lv    Male    51.0        N

[200 rows x 5 columns]

In [22]:
s = pd.Series([np.nan, 1, np.nan, np.nan, 2, np.nan],
               list('aaabcd'))

In [23]:
s

a    NaN
a    1.0
a    NaN
b    NaN
c    2.0
d    NaN
dtype: float64

In [24]:
s.fillna(method='ffill')

a    NaN
a    1.0
a    1.0
b    1.0
c    2.0
d    2.0
dtype: float64

In [25]:
s.fillna(method='ffill', limit=1) # 连续出现的缺失，最多填充一次

a    NaN
a    1.0
a    1.0
b    NaN
c    2.0
d    2.0
dtype: float64

In [27]:
s.fillna(s.mean())

a    1.5
a    1.0
a    1.5
b    1.5
c    2.0
d    1.5
dtype: float64

In [38]:
df.groupby('Grade')['Height'].transform(lambda x:x).head()

0    158.9
1    166.5
2    188.9
3      NaN
4    174.0
Name: Height, dtype: float64

In [39]:
df.groupby('Grade')['Height'].transform('mean').head()

0    163.002128
1    163.002128
2    163.969811
3    163.075862
4    163.075862
Name: Height, dtype: float64

In [28]:
df.groupby('Grade')['Height'].transform(
                     lambda x: x.fillna(x.mean())).head()

0    158.900000
1    166.500000
2    188.900000
3    163.075862
4    174.000000
Name: Height, dtype: float64

In [41]:
s = pd.Series([np.nan, np.nan, 1,
               np.nan, np.nan, np.nan,
               2, np.nan, np.nan])

In [42]:
s

0    NaN
1    NaN
2    1.0
3    NaN
4    NaN
5    NaN
6    2.0
7    NaN
8    NaN
dtype: float64

In [48]:
s.interpolate(limit_direction='backward', limit=1).values

array([ nan, 1.  , 1.  ,  nan,  nan, 1.75, 2.  ,  nan,  nan])

In [49]:
s.interpolate(limit_direction='both', limit=1).values

array([ nan, 1.  , 1.  , 1.25,  nan, 1.75, 2.  , 2.  ,  nan])

In [47]:
s.interpolate('nearest').values

array([nan, nan,  1.,  1.,  1.,  2.,  2., nan, nan])

In [50]:
s = pd.Series([0,np.nan,10],index=[0,1,10])

In [51]:
s

0      0.0
1      NaN
10    10.0
dtype: float64

In [52]:
s.interpolate(method='index')

0      0.0
1      1.0
10    10.0
dtype: float64

In [53]:
s = pd.Series(['a', 'b'])
s_bool = pd.Series([True, np.nan])

In [54]:
s

0    a
1    b
dtype: object

In [55]:
s_bool

0    True
1     NaN
dtype: object

In [56]:
s_boolean = pd.Series([True, np.nan]).astype('boolean')

In [57]:
s_boolean

0    True
1    <NA>
dtype: boolean

In [60]:
s = pd.Series(['a', 'b'])
s_bool = pd.Series([True, np.nan])
s_boolean = pd.Series([True, np.nan]).astype('boolean')

In [61]:
s_boolean & True

0    True
1    <NA>
dtype: boolean

In [62]:
s_bool & True

0     True
1    False
dtype: bool

In [63]:
df = pd.read_csv('data/learn_pandas.csv')
df = df.convert_dtypes()
print(df.dtypes)

School          string
Grade           string
Name            string
Gender          string
Height         Float64
Weight           Int64
Transfer        string
Test_Number      Int64
Test_Date       string
Time_Record     string
dtype: object


In [64]:
df_nan = pd.DataFrame({'category':['a','a','b',np.nan,np.nan],
                       'value':[1,3,5,7,9]})

In [65]:
df_nan

category  value
0        a      1
1        a      3
2        b      5
3      NaN      7
4      NaN      9

In [68]:
df_nan.groupby('category')['value'].mean()

category
a    2
b    5
Name: value, dtype: int64

In [69]:
df_nan.groupby('category',
                dropna=False)['value'].mean()

category
a      2
b      5
NaN    8
Name: value, dtype: int64

In [70]:
pd.get_dummies(df_nan.category, dummy_na=True)

a  b  NaN
0  1  0    0
1  1  0    0
2  0  1    0
3  0  0    1
4  0  0    1

In [71]:
pd.get_dummies(df_nan.category)

a  b
0  1  0
1  1  0
2  0  1
3  0  0
4  0  0